# CVE-2013-1633


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2013-08-06 02:52:00 | 2013-10-11 13:59:00 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | easy_install in setuptools before 0.7 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to the default use of the product. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:python:setuptools:*:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.46:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.41:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.42:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.47:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.48:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.49:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.44:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.43:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.40:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:setuptools:0.6.45:*:*:*:*:*:*:* | [] | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 6.8 | MEDIUM | 6.4 | 8.6 | AV:N/AC:M/Au:N/C:P/I:P/A:P | 2.0 | NETWORK | MEDIUM | NONE | 1 | False | False | False | PARTIAL | PARTIAL | PARTIAL |

## Problem Type
CWE-20

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/|http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/|MISC|[]
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://pypi.python.org/pypi/setuptools/0.9.8#changes|https://pypi.python.org/pypi/setuptools/0.9.8#changes|CONFIRM|['Vendor Advisory']
