# CVE-2013-1629


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2013-08-06 | 2021-03-15 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | "pip before 1.3 uses HTTP to retrieve packages from the PyPI repository, and does not perform integrity checks on package contents, which allows man-in-the-middle attackers to execute arbitrary code via a crafted response to a ""pip install"" operation." |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:pypa:pip:*:*:*:*:*:*:*:* | []    1.3 | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 6.8 | MEDIUM | 6.4 | 8.6 | AV:N/AC:M/Au:N/C:P/I:P/A:P | 2.0 | NETWORK | MEDIUM | NONE | False | False | False | False | PARTIAL | PARTIAL | PARTIAL |

## Problem Type
CWE-20

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/pypa/pip/issues/425|https://github.com/pypa/pip/issues/425|CONFIRM|['Third Party Advisory']
https://github.com/pypa/pip/pull/791/files|https://github.com/pypa/pip/pull/791/files|CONFIRM|['Patch', 'Third Party Advisory']
http://www.pip-installer.org/en/latest/installing.html|http://www.pip-installer.org/en/latest/installing.html|CONFIRM|['Vendor Advisory']
http://www.pip-installer.org/en/latest/news.html#changelog|http://www.pip-installer.org/en/latest/news.html#changelog|CONFIRM|['Release Notes', 'Vendor Advisory']
http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/|http://www.reddit.com/r/Python/comments/17rfh7/warning_dont_use_pip_in_an_untrusted_network_a/|MISC|['Exploit', 'Third Party Advisory']
https://bugzilla.redhat.com/show_bug.cgi?id=968059|https://bugzilla.redhat.com/show_bug.cgi?id=968059|CONFIRM|['Issue Tracking', 'Third Party Advisory']
