# CVE-2014-1604


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2014-01-28 | 2017-08-29 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | The parser cache functionality in parsergenerator.py in RPLY (aka python-rply) before 0.7.1 allows local users to spoof cache data by pre-creating a temporary rply-*.json file with a predictable name. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:python:rply:*:*:*:*:*:*:*:* | []  0.7.0   | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 2.1 | LOW | 2.9 | 3.9 | AV:L/AC:L/Au:N/C:N/I:P/A:N | 2.0 | LOCAL | LOW | NONE | False | False | False | False | NONE | PARTIAL | NONE |

## Problem Type
NVD-CWE-Other

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[oss-security] 20140114 Fwd: [Python-modules-team] Bug#735263: python-rply: insecure use of /tmp|http://www.openwall.com/lists/oss-security/2014/01/17/8|MLIST|[]
102202|http://www.osvdb.org/102202|OSVDB|[]
https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c|https://github.com/alex/rply/commit/fc9bbcd25b0b4f09bbd6339f710ad24c129d5d7c|CONFIRM|[]
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263|http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=735263|CONFIRM|[]
56429|http://secunia.com/advisories/56429|SECUNIA|['Vendor Advisory']
[oss-security] 20140117 Re: Fwd: [Python-modules-team] Bug#735263: python-rply: insecure use of /tmp|http://www.openwall.com/lists/oss-security/2014/01/18/4|MLIST|[]
rply-cve20141604-insecure-permissions(90593)|https://exchange.xforce.ibmcloud.com/vulnerabilities/90593|XF|[]
