# CVE-2021-4189


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-08-24 | 2022-11-04 | secalert@redhat.com | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | A flaw was found in Python, specifically in the FTP (File Transfer Protocol) client library in PASV (passive) mode. The issue is how the FTP client trusts the host from the PASV response by default. This flaw allows an attacker to set up a malicious FTP server that can trick FTP clients into connecting back to a given IP address and port. This vulnerability could lead to FTP client scanning ports, which otherwise would not have been possible. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | 3.9.0   | 3.9.3 | OR |
| True  cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | 3.8.0   | 3.8.9 | OR |
| True  cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | 3.7.0   | 3.7.11 | OR |
| True  cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | 3.6.0   | 3.6.14 | OR |
| True  cpe:2.3:a:python:python:3.10.0:-:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:debian:debian_linux:11.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:redhat:software_collections:-:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 5.3 | MEDIUM | 1.4 | 3.9 | CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N | 3.1 | NETWORK | LOW | NONE | NONE | UNCHANGED | LOW | NONE | NONE |

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
CWE-252

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e|https://github.com/python/cpython/commit/0ab152c6b5d95caa2dc1a30fa96e10258b5f188e|MISC|['Patch', 'Third Party Advisory']
https://access.redhat.com/security/cve/CVE-2021-4189|https://access.redhat.com/security/cve/CVE-2021-4189|MISC|['Third Party Advisory']
https://bugzilla.redhat.com/show_bug.cgi?id=2036020|https://bugzilla.redhat.com/show_bug.cgi?id=2036020|MISC|['Issue Tracking', 'Patch', 'Third Party Advisory']
https://security-tracker.debian.org/tracker/CVE-2021-4189|https://security-tracker.debian.org/tracker/CVE-2021-4189|MISC|['Third Party Advisory']
https://bugs.python.org/issue43285|https://bugs.python.org/issue43285|MISC|['Patch', 'Vendor Advisory']
https://python-security.readthedocs.io/vuln/ftplib-pasv.html|https://python-security.readthedocs.io/vuln/ftplib-pasv.html|MISC|['Patch', 'Third Party Advisory']
https://security.netapp.com/advisory/ntap-20221104-0004/|https://security.netapp.com/advisory/ntap-20221104-0004/|CONFIRM|[]
