# CVE-2016-10149


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2017-03-24 | 2018-01-05 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier allows remote attackers to read arbitrary files via a crafted SAML XML request or response. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:pysaml2_project:pysaml2:*:*:*:*:*:*:*:* | []  4.4.0   | OR |
| True  cpe:2.3:o:debian:debian_linux:8.0:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 7.5 | HIGH | 3.6 | 3.9 | CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N | 3.0 | NETWORK | LOW | NONE | NONE | UNCHANGED | HIGH | NONE | NONE |

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 5.0 | MEDIUM | 2.9 | 10.0 | AV:N/AC:L/Au:N/C:P/I:N/A:N | 2.0 | NETWORK | LOW | NONE | False | False | False | False | PARTIAL | NONE | NONE |

## Problem Type
CWE-611

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/rohe/pysaml2/pull/379|https://github.com/rohe/pysaml2/pull/379|CONFIRM|['Issue Tracking', 'Patch', 'Third Party Advisory']
https://github.com/rohe/pysaml2/issues/366|https://github.com/rohe/pysaml2/issues/366|MISC|['Issue Tracking', 'Patch', 'Third Party Advisory']
https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b|https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b|CONFIRM|['Issue Tracking', 'Patch', 'Third Party Advisory']
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716|https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716|CONFIRM|['Issue Tracking', 'Patch', 'Third Party Advisory']
[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack|http://www.openwall.com/lists/oss-security/2017/01/19/5|MLIST|['Mailing List', 'Patch', 'Third Party Advisory']
DSA-3759|http://www.debian.org/security/2017/dsa-3759|DEBIAN|['Third Party Advisory']
97692|http://www.securityfocus.com/bid/97692|BID|[]
RHSA-2017:0938|https://access.redhat.com/errata/RHSA-2017:0938|REDHAT|[]
RHSA-2017:0937|https://access.redhat.com/errata/RHSA-2017:0937|REDHAT|[]
RHSA-2017:0936|https://access.redhat.com/errata/RHSA-2017:0936|REDHAT|[]
