# CVE-2022-45061


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-11-09 | 2022-11-09 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | An issue was discovered in Python before 3.11.1. An unnecessary quadratic algorithm exists in one path when processing some inputs to the IDNA (RFC 3490) decoder, such that a crafted, unreasonably long name being presented to the decoder could lead to a CPU denial of service. Hostnames are often supplied by remote servers that could be controlled by a malicious actor; in such a scenario, they could trigger excessive CPU consumption on the client attempting to make use of an attacker-supplied supposed hostname. For example, the attack payload could be placed in the Location header of an HTTP response with status code 302. A fix is planned in 3.11.1, 3.10.9, 3.9.16, 3.8.16, and 3.7.16. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:python:python:3.11.0:alpha2:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:alpha3:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:alpha4:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:alpha5:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:alpha6:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:alpha1:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:beta2:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:beta3:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:beta4:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | []  3.7.15   | OR |
| True  cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | 3.8.0 | 3.8.15   | OR |
| True  cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | 3.9.0 | 3.9.15   | OR |
| True  cpe:2.3:a:python:python:3.11.0:-:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | 3.10.0 | 3.10.8   | OR |
| True  cpe:2.3:a:python:python:3.11.0:alpha7:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:beta1:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:beta5:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:rc1:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:python:python:3.11.0:rc2:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 7.5 | HIGH | 3.6 | 3.9 | CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H | 3.1 | NETWORK | LOW | NONE | NONE | UNCHANGED | NONE | NONE | HIGH |

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
CWE-400

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/python/cpython/issues/98433|https://github.com/python/cpython/issues/98433|MISC|['Exploit', 'Patch', 'Third Party Advisory']
