# CVE-2019-12781


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2019-07-01 | 2020-08-24 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10, and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the proxy connects to Django via HTTPS. In other words, django.http.HttpRequest.scheme has incorrect behavior when a client uses HTTP. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:* | [] | 1.11   | 1.11.22 | OR |
| True  cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:* | [] | 2.1   | 2.1.10 | OR |
| True  cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:* | [] | 2.2   | 2.2.3 | OR |
| True  cpe:2.3:o:canonical:ubuntu_linux:16.04:*:*:*:lts:*:*:* | []     | OR |
| True  cpe:2.3:o:debian:debian_linux:9.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:canonical:ubuntu_linux:18.04:*:*:*:lts:*:*:* | []     | OR |
| True  cpe:2.3:o:canonical:ubuntu_linux:18.10:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:canonical:ubuntu_linux:19.04:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 5.3 | MEDIUM | 1.4 | 3.9 | CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N | 3.0 | NETWORK | LOW | NONE | NONE | UNCHANGED | LOW | NONE | NONE |

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 5.0 | MEDIUM | 2.9 | 10.0 | AV:N/AC:L/Au:N/C:P/I:N/A:N | 2.0 | NETWORK | LOW | NONE | False | False | False | False | PARTIAL | NONE | NONE |

## Problem Type
CWE-319

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ|https://groups.google.com/forum/#!topic/django-announce/Is4kLY9ZcZQ|MISC|['Third Party Advisory']
https://www.djangoproject.com/weblog/2019/jul/01/security-releases/|https://www.djangoproject.com/weblog/2019/jul/01/security-releases/|CONFIRM|['Patch', 'Vendor Advisory']
https://docs.djangoproject.com/en/dev/releases/security/|https://docs.djangoproject.com/en/dev/releases/security/|MISC|['Patch', 'Vendor Advisory']
[oss-security] 20190701 Django: CVE-2019-12781: Incorrect HTTP detection with reverse-proxy connecting via HTTPS|http://www.openwall.com/lists/oss-security/2019/07/01/3|MLIST|['Mailing List', 'Patch', 'Third Party Advisory']
USN-4043-1|https://usn.ubuntu.com/4043-1/|UBUNTU|['Third Party Advisory']
109018|http://www.securityfocus.com/bid/109018|BID|['Third Party Advisory']
https://security.netapp.com/advisory/ntap-20190705-0002/|https://security.netapp.com/advisory/ntap-20190705-0002/|CONFIRM|['Third Party Advisory']
DSA-4476|https://www.debian.org/security/2019/dsa-4476|DEBIAN|['Third Party Advisory']
20190708 [SECURITY] [DSA 4476-1] python-django security update|https://seclists.org/bugtraq/2019/Jul/10|BUGTRAQ|['Third Party Advisory']
FEDORA-2019-d9aa58d863|https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5VXXWIOQGXOB7JCGJ3CVUW673LDHKEYL/|FEDORA|[]
openSUSE-SU-2019:1839|http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00006.html|SUSE|[]
openSUSE-SU-2019:1872|http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00025.html|SUSE|[]
