# CVE-2022-35940


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-09-16 20:15:00 | 2022-09-16 21:37:00 | security-advisories@github.com | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | TensorFlow is an open source platform for machine learning. The `RaggedRangOp` function takes an argument `limits` that is eventually used to construct a `TensorShape` as an `int64`. If `limits` is a very large float, it can overflow when converted to an `int64`. This triggers an `InvalidArgument` but also throws an abort signal that crashes the program. We have patched the issue in GitHub commit 37cefa91bee4eace55715eeef43720b958a01192. The fix will be included in TensorFlow 2.10.0. We will also cherrypick this commit on TensorFlow 2.9.1, TensorFlow 2.8.1, and TensorFlow 2.7.2, as these are also affected and still in supported range. There are no known workarounds for this issue. |

## Configurations
*** Not Provided ***

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
CWE-190

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/tensorflow/tensorflow/security/advisories/GHSA-x989-q2pq-4q5x|https://github.com/tensorflow/tensorflow/security/advisories/GHSA-x989-q2pq-4q5x|CONFIRM|[]
https://github.com/tensorflow/tensorflow/commit/37cefa91bee4eace55715eeef43720b958a01192|https://github.com/tensorflow/tensorflow/commit/37cefa91bee4eace55715eeef43720b958a01192|MISC|[]
https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/kernels/ragged_range_op.cc#L74-L88|https://github.com/tensorflow/tensorflow/blob/0b6b491d21d6a4eb5fbab1cca565bc1e94ca9543/tensorflow/core/kernels/ragged_range_op.cc#L74-L88|MISC|[]
