# CVE-2010-3492


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2010-10-19 20:00:00 | 2019-10-29 00:56:00 | cve@mitre.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | The asyncore module in Python before 3.2 does not properly handle unsuccessful calls to the accept function, and does not have accompanying documentation describing how daemon applications should handle unsuccessful calls to the accept function, which makes it easier for remote attackers to conduct denial of service attacks that terminate these applications via network connections. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:*:*:*:*:*:*:*:* | [] | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 5.0 | MEDIUM | 2.9 | 10.0 | AV:N/AC:L/Au:N/C:N/I:N/A:P | 2.0 | NETWORK | LOW | NONE | 0 | False | False | False | NONE | NONE | PARTIAL |

## Problem Type
NVD-CWE-Other

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
[oss-security] 20100924 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/24/3|MLIST|['Mailing List', 'Third Party Advisory']
[oss-security] 20100910 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/11/2|MLIST|['Mailing List', 'Third Party Advisory']
[oss-security] 20100909 CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/09/6|MLIST|['Mailing List', 'Third Party Advisory']
[oss-security] 20100922 Re: CVE Request -- Python -- accept() implementation in async core is broken => more subcases|http://www.openwall.com/lists/oss-security/2010/09/22/3|MLIST|['Mailing List', 'Third Party Advisory']
http://bugs.python.org/issue6706|http://bugs.python.org/issue6706|CONFIRM|['Patch', 'Vendor Advisory']
MDVSA-2010:216|http://www.mandriva.com/security/advisories?name=MDVSA-2010:216|MANDRIVA|['Third Party Advisory']
MDVSA-2010:215|http://www.mandriva.com/security/advisories?name=MDVSA-2010:215|MANDRIVA|['Third Party Advisory']
oval:org.mitre.oval:def:12111|https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A12111|OVAL|['Third Party Advisory']
