# CVE-2013-2099


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2013-10-09 14:53:00 | 2016-06-09 01:59:00 | secalert@redhat.com | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | Algorithmic complexity vulnerability in the ssl.match_hostname function in Python 3.2.x, 3.3.x, and earlier, and unspecified versions of python-backports-ssl_match_hostname as used for older Python versions, allows remote attackers to cause a denial of service (CPU consumption) via multiple wildcard characters in the common name in a certificate. |

## Configurations
| Vulnerable | CPE 23 URI | CPE Name | Operator |
| ---------- | ---------- | -------- | -------- |
| True | cpe:2.3:a:python:python:3.3.2:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:3.2.2:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:3.2.5:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:3.2.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:3.2.0:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:3.3.1:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:3.2.3:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:3.3.0:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:a:python:python:3.2.4:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:o:canonical:ubuntu_linux:13.04:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:o:canonical:ubuntu_linux:12.10:*:*:*:*:*:*:* | [] | OR |
| True | cpe:2.3:o:canonical:ubuntu_linux:12.04:-:lts:*:*:*:*:* | [] | OR |

## CVSSv3 Information
*** Not Provided/Calculated ***

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 4.3 | MEDIUM | 2.9 | 8.6 | AV:N/AC:M/Au:N/C:N/I:N/A:P | 2.0 | NETWORK | MEDIUM | NONE | 0 | False | False | False | NONE | NONE | PARTIAL |

## Problem Type
CWE-399

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
55116|http://secunia.com/advisories/55116|SECUNIA|['Vendor Advisory']
55107|http://secunia.com/advisories/55107|SECUNIA|['Vendor Advisory']
https://bugzilla.redhat.com/show_bug.cgi?id=963260|https://bugzilla.redhat.com/show_bug.cgi?id=963260|MISC|[]
USN-1983-1|http://www.ubuntu.com/usn/USN-1983-1|UBUNTU|[]
USN-1985-1|http://www.ubuntu.com/usn/USN-1985-1|UBUNTU|[]
http://bugs.python.org/issue17980|http://bugs.python.org/issue17980|CONFIRM|['Patch']
[oss-security] 20130515 Re: CVE Request (minor) -- Python 3.2: DoS when matching  certificate with many '*' wildcard characters {was: CVE Request  (minor) --  python-backports-ssl_match_hostname: Denial of service when matching  certificate with many '*' wildcard characters }|http://www.openwall.com/lists/oss-security/2013/05/16/6|MLIST|[]
USN-1984-1|http://www.ubuntu.com/usn/USN-1984-1|UBUNTU|[]
RHSA-2014:1690|http://rhn.redhat.com/errata/RHSA-2014-1690.html|REDHAT|[]
RHSA-2016:1166|https://access.redhat.com/errata/RHSA-2016:1166|REDHAT|[]
