# CVE-2022-0718


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2022-08-29 | 2022-09-13 | secalert@redhat.com | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( "" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext." |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:openstack:oslo.utils:*:*:*:*:*:*:*:* | []    4.10.1 | OR |
| True  cpe:2.3:a:openstack:oslo.utils:4.12.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:redhat:openshift_container_platform:4.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:a:redhat:openstack_platform:16.1:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:debian:debian_linux:10.0:*:*:*:*:*:*:* | []     | OR |
| True  cpe:2.3:o:debian:debian_linux:11.0:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 4.9 | MEDIUM | 3.6 | 1.2 | CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N | 3.1 | NETWORK | LOW | HIGH | NONE | UNCHANGED | HIGH | NONE | NONE |

## CVSSv2 Information
*** Not Provided/Calculated ***

## Problem Type
CWE-522

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://security-tracker.debian.org/tracker/CVE-2022-0718|https://security-tracker.debian.org/tracker/CVE-2022-0718|MISC|['Patch', 'Third Party Advisory']
https://bugzilla.redhat.com/show_bug.cgi?id=2056850|https://bugzilla.redhat.com/show_bug.cgi?id=2056850|MISC|['Issue Tracking', 'Patch', 'Third Party Advisory']
https://access.redhat.com/security/cve/CVE-2022-0718|https://access.redhat.com/security/cve/CVE-2022-0718|MISC|['Third Party Advisory']
https://bugs.launchpad.net/oslo.utils/+bug/1949623|https://bugs.launchpad.net/oslo.utils/+bug/1949623|MISC|['Exploit', 'Issue Tracking', 'Patch', 'Third Party Advisory']
https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa|https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa|MISC|['Patch', 'Vendor Advisory']
[debian-lts-announce] 20220913 [SECURITY] [DLA 3106-1] python-oslo.utils security update|https://lists.debian.org/debian-lts-announce/2022/09/msg00015.html|MLIST|[]
