# CVE-2016-10127


## Metadata
| Published | Last Modified | Assigner | Version | Format |
| --------- | ------------- | -------- | ------- | ------ |
| 2017-03-03 | 2017-03-08 | security@debian.org | 4.0 | MITRE | 

## Description
| Language | Description |
| -------- | ----------- |
| en | PySAML2 allows remote attackers to conduct XML external entity (XXE) attacks via a crafted SAML XML request or response. |

## Configurations
| Vulnerable | CPE 22 URI | CPE 23 URI | CPE Name | Version Start Including | Version End Including | Version Start Excluding | Version End Excluding | Operator |
| ---------- | ---------- | ---------- | -------- | ----------------------- | --------------------- | ----------------------- | --------------------- | -------- |
| True  cpe:2.3:a:pysaml2_project:pysaml2:-:*:*:*:*:*:*:* | []     | OR |

## CVSSv3 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Attack Vector | Attack Complexity | Privileges Required | User Interaction | Scope | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | ------------------- | ---------------- | ----- | ---------------------- | ---------------- | ------------------- |
| 9.0 | CRITICAL | 6.0 | 2.3 | CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H | 3.0 | NETWORK | LOW | LOW | REQUIRED | CHANGED | HIGH | HIGH | HIGH |

## CVSSv2 Information
| Score | Severity | Impact Score | Exploitability Score | Vector String | Version | Access Vector | Access Complexity | Authentication | User Interaction Required | Obtain All Privilge | Obtain User Privilege | Obtain Other Privilege | Confidentiality Impact | Integrity Impact | Availability Impact |
| ----- | -------- | ------------ | -------------------- | ------------- | ------- | ------------- | ----------------- | -------------- | ------------------------- | ------------------- | --------------------- | ---------------------- | ---------------------- | ---------------- | ------------------- |
| 6.8 | MEDIUM | 6.4 | 8.6 | AV:N/AC:M/Au:N/C:P/I:P/A:P | 2.0 | NETWORK | MEDIUM | NONE | True | False | False | False | PARTIAL | PARTIAL | PARTIAL |

## Problem Type
CWE-611

## References
| Name | Reference URL | Reference Source | Tags |
| ---- | ------------- | ---------------- | ---- |
https://github.com/rohe/pysaml2/pull/379|https://github.com/rohe/pysaml2/pull/379|MISC|['Issue Tracking', 'Patch']
https://github.com/rohe/pysaml2/issues/366|https://github.com/rohe/pysaml2/issues/366|MISC|['Issue Tracking', 'Patch']
https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b|https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b|MISC|['Patch']
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716|https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716|MISC|['Mailing List', 'Third Party Advisory']
[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack|http://www.openwall.com/lists/oss-security/2017/01/19/5|MLIST|['Mailing List', 'Third Party Advisory']
95376|http://www.securityfocus.com/bid/95376|BID|['VDB Entry']
